from __future__ import annotations

from app.subtitle.styles.models import SubtitleStyle


DEFAULT_SUBTITLE_STYLES: list[SubtitleStyle] = [
    SubtitleStyle(
        key="tiktok_bold",
        name="TikTok Bold",
        category="short_form",
        font_family="Montserrat",
        font_size=76,
        stroke_width=6,
        highlight_color="#FFD400",
        position="bottom",
        animation="pop",
        word_animation="highlight",
    ),
    SubtitleStyle(
        key="hormozi",
        name="Hormozi",
        category="education",
        font_family="Anton",
        font_size=72,
        text_color="#FFFFFF",
        stroke_color="#000000",
        stroke_width=5,
        highlight_color="#00FF66",
        position="center_bottom",
        animation="scale",
        word_animation="keyword_pop",
    ),
    SubtitleStyle(
        key="mrbeast",
        name="MrBeast",
        category="viral",
        font_family="Bebas Neue",
        font_size=82,
        text_color="#FFFFFF",
        stroke_color="#000000",
        stroke_width=7,
        highlight_color="#FF3131",
        position="center",
        animation="bounce",
        word_animation="shake",
    ),
    SubtitleStyle(
        key="podcast_clean",
        name="Podcast Clean",
        category="podcast",
        font_family="Inter",
        font_size=54,
        stroke_width=3,
        highlight_color="#7DD3FC",
        position="bottom",
        animation="fade",
        word_animation="none",
    ),
    SubtitleStyle(
        key="minimal",
        name="Minimal",
        category="minimal",
        font_family="Inter",
        font_size=48,
        stroke_width=0,
        shadow=False,
        highlight_color="#FFFFFF",
        position="bottom",
        animation="fade",
        word_animation="none",
    ),
    SubtitleStyle(
        key="gaming",
        name="Gaming",
        category="gaming",
        font_family="Luckiest Guy",
        font_size=80,
        stroke_width=7,
        highlight_color="#FF00FF",
        position="center_bottom",
        animation="bounce",
        word_animation="shake",
    ),
    SubtitleStyle(
        key="corporate",
        name="Corporate",
        category="business",
        font_family="Roboto",
        font_size=50,
        stroke_width=2,
        highlight_color="#2563EB",
        position="bottom",
        animation="fade",
        word_animation="none",
    ),
    SubtitleStyle(
        key="luxury",
        name="Luxury",
        category="premium",
        font_family="Playfair Display",
        font_size=56,
        text_color="#F8F1E5",
        stroke_color="#111111",
        stroke_width=2,
        highlight_color="#D4AF37",
        position="bottom",
        animation="fade",
        word_animation="none",
    ),
]