export const TIMELINE_LINK_GROUP_SYNC_CONTRACT_VERSION = "16.8.8.5" as const;

export type LinkableClipKind = "video"|"audio"|"subtitle"|"overlay"|"effect"|"image"|"generated"|"custom";
export type TimelineSyncMode = "start"|"end"|"range"|"source"|"custom";
export type TimelineLinkMemberRole = "anchor"|"linked";
export type TimelineLinkGroupOperation = "create-group"|"add-members"|"remove-members"|"merge-groups"|"split-group"|"unlink-group"|"change-anchor"|"capture-sync"|"validate-sync"|"repair-sync"|"relink-after-split";
export type TimelineSynchronizationState = "in-sync"|"within-tolerance"|"out-of-sync"|"missing-clip"|"invalid-relation"|"disabled";
export type TimelineSyncRepairStrategy = "move-linked-to-anchor"|"move-anchor-to-linked"|"move-entire-group"|"recapture-current-offset"|"ignore";
export type TimelineLinkGroupSyncStatus = "idle"|"editing"|"previewing"|"validating"|"repairing"|"blocked"|"committed"|"cancelled"|"disposed";

export interface LinkableTimelineClip { readonly clipId:string; readonly trackId:string; readonly kind:LinkableClipKind; readonly timelineStartFrame:number; readonly timelineEndFrame:number; readonly sourceStartFrame?:number|null; readonly sourceEndFrame?:number|null; readonly sourceDurationFrames?:number|null; readonly linkGroupId?:string|null; readonly locked?:boolean; readonly enabled?:boolean; }
export interface TimelineLinkGroup { readonly groupId:string; readonly anchorClipId:string; readonly clipIds:readonly string[]; readonly createdFromGroupIds:readonly string[]; readonly syncEnabled:boolean; readonly locked:boolean; readonly version:number; }
export interface TimelineLinkMembership { readonly clipId:string; readonly groupId:string; readonly role:TimelineLinkMemberRole; }
export interface TimelineSyncRelation { readonly relationId:string; readonly groupId:string; readonly anchorClipId:string; readonly linkedClipId:string; readonly timelineStartOffsetFrames:number; readonly timelineEndOffsetFrames:number; readonly sourceStartOffsetFrames:number|null; readonly sourceEndOffsetFrames:number|null; readonly mode:TimelineSyncMode; readonly toleranceFrames:number; readonly enabled:boolean; }
export interface TimelineGroupSplitPartition { readonly targetGroupId:string; readonly clipIds:readonly string[]; readonly anchorClipId?:string|null; }
export interface TimelineGroupSplitPlan { readonly sourceGroupId:string; readonly partitions:readonly TimelineGroupSplitPartition[]; readonly unlinkClipIds?:readonly string[]; }
export interface TimelineRelinkFragment { readonly originalClipId:string; readonly fragmentClipId:string; readonly timelineStartFrame:number; readonly timelineEndFrame:number; readonly side:"left"|"right"|"middle"; }
export interface TimelineRelinkAfterSplitPlan { readonly sourceGroupId:string; readonly fragments:readonly TimelineRelinkFragment[]; readonly targetGroups:readonly { readonly targetGroupId:string; readonly fragmentClipIds:readonly string[]; readonly inheritedClipIds?:readonly string[]; readonly anchorClipId?:string|null; }[]; }
export interface TimelineLinkGroupSyncConfiguration { readonly framesPerSecond:number; readonly defaultToleranceFrames?:number; readonly defaultSyncMode?:TimelineSyncMode; readonly allowSingleMemberGroup?:boolean; readonly dissolveSingleMemberGroup?:boolean; readonly preserveStartOffsets?:boolean; readonly preserveEndOffsets?:boolean; readonly preserveSourceOffsets?:boolean; readonly autoIncludeExistingGroupMembers?:boolean; readonly autoSelectAnchor?:boolean; readonly autoRepairWithinTolerance?:boolean; readonly blockLockedClipChanges?:boolean; readonly blockLockedGroupChanges?:boolean; readonly clampRepairToTimelineStart?:boolean; readonly timelineStartFrame?:number; readonly timelineEndFrame?:number|null; }
export interface BeginTimelineLinkGroupRequest { readonly sessionId:string; readonly operation:TimelineLinkGroupOperation; readonly clips:readonly LinkableTimelineClip[]; readonly groups:readonly TimelineLinkGroup[]; readonly relations?:readonly TimelineSyncRelation[]; readonly selectedClipIds?:readonly string[]; readonly selectedGroupIds?:readonly string[]; readonly targetGroupId?:string|null; readonly requestedAnchorClipId?:string|null; readonly splitPlan?:TimelineGroupSplitPlan|null; readonly relinkPlan?:TimelineRelinkAfterSplitPlan|null; }
export interface TimelineLinkGroupSyncSession { readonly sessionId:string; readonly operation:TimelineLinkGroupOperation; readonly selectedClipIds:readonly string[]; readonly selectedGroupIds:readonly string[]; readonly targetGroupId:string|null; readonly anchorClipId:string|null; readonly startedAtVersion:number; }
export interface TimelineSyncValidation { readonly relationId:string; readonly groupId:string; readonly anchorClipId:string; readonly linkedClipId:string; readonly state:TimelineSynchronizationState; readonly expectedStartFrame:number; readonly actualStartFrame:number; readonly startDriftFrames:number; readonly expectedEndFrame:number|null; readonly actualEndFrame:number|null; readonly endDriftFrames:number|null; readonly toleranceFrames:number; readonly blocking:boolean; }
export interface TimelineSyncRepairRequest { readonly groupId:string; readonly relationIds?:readonly string[]; readonly strategy:TimelineSyncRepairStrategy; readonly primaryClipId?:string|null; readonly includeWithinTolerance?:boolean; }
export interface TimelineSyncRepairChange { readonly clipId:string; readonly trackId:string; readonly originalStartFrame:number; readonly originalEndFrame:number; readonly previewStartFrame:number; readonly previewEndFrame:number; readonly deltaFrames:number; readonly reason:string; }
export type TimelineLinkGroupConflictCode = "missing-session-id"|"invalid-operation"|"missing-selection"|"missing-target-group-id"|"unknown-clip"|"unknown-group"|"unknown-relation"|"duplicate-clip-id"|"duplicate-group-id"|"duplicate-relation-id"|"duplicate-membership"|"clip-already-linked"|"clip-in-multiple-groups"|"anchor-not-in-group"|"missing-anchor"|"locked-clip"|"locked-group"|"insufficient-group-members"|"single-member-group-not-allowed"|"invalid-timeline-range"|"invalid-source-range"|"invalid-tolerance"|"invalid-sync-relation"|"sync-out-of-tolerance"|"repair-out-of-bounds"|"repair-unresolved"|"invalid-split-plan"|"split-partition-overlap"|"split-member-missing"|"target-group-id-conflict"|"empty-change-set";
export interface TimelineLinkGroupConflict { readonly code:TimelineLinkGroupConflictCode; readonly message:string; readonly clipId?:string|null; readonly groupId?:string|null; readonly relationId?:string|null; readonly blocking:boolean; }
export interface TimelineLinkGroupChangeSet { readonly createdGroups:readonly TimelineLinkGroup[]; readonly updatedGroups:readonly TimelineLinkGroup[]; readonly removedGroupIds:readonly string[]; readonly createdRelations:readonly TimelineSyncRelation[]; readonly updatedRelations:readonly TimelineSyncRelation[]; readonly removedRelationIds:readonly string[]; readonly membershipsAdded:readonly TimelineLinkMembership[]; readonly membershipsRemoved:readonly TimelineLinkMembership[]; readonly repairChanges:readonly TimelineSyncRepairChange[]; }
export interface TimelineLinkGroupOperationPreview { readonly operation:TimelineLinkGroupOperation; readonly changeSet:TimelineLinkGroupChangeSet; readonly resultingGroups:readonly TimelineLinkGroup[]; readonly resultingRelations:readonly TimelineSyncRelation[]; readonly resultingMemberships:readonly TimelineLinkMembership[]; readonly syncValidations:readonly TimelineSyncValidation[]; readonly conflicts:readonly TimelineLinkGroupConflict[]; readonly blocked:boolean; }
export interface TimelineSyncRepairPreview { readonly groupId:string; readonly strategy:TimelineSyncRepairStrategy; readonly changes:readonly TimelineSyncRepairChange[]; readonly validationsBefore:readonly TimelineSyncValidation[]; readonly validationsAfter:readonly TimelineSyncValidation[]; readonly repairedRelationIds:readonly string[]; readonly unresolvedRelationIds:readonly string[]; readonly clamped:boolean; readonly blocked:boolean; readonly conflicts:readonly TimelineLinkGroupConflict[]; }
export interface TimelineLinkGroupCommitResult { readonly sessionId:string; readonly operation:TimelineLinkGroupOperation; readonly committed:boolean; readonly changeSet:TimelineLinkGroupChangeSet; readonly resultingGroups:readonly TimelineLinkGroup[]; readonly resultingRelations:readonly TimelineSyncRelation[]; readonly resultingMemberships:readonly TimelineLinkMembership[]; readonly conflicts:readonly TimelineLinkGroupConflict[]; }
export interface TimelineLinkGroupSyncSnapshot { readonly contractVersion:typeof TIMELINE_LINK_GROUP_SYNC_CONTRACT_VERSION; readonly version:number; readonly status:TimelineLinkGroupSyncStatus; readonly configured:boolean; readonly clips:readonly LinkableTimelineClip[]; readonly groups:readonly TimelineLinkGroup[]; readonly relations:readonly TimelineSyncRelation[]; readonly memberships:readonly TimelineLinkMembership[]; readonly session:TimelineLinkGroupSyncSession|null; readonly preview:TimelineLinkGroupOperationPreview|null; readonly repairPreview:TimelineSyncRepairPreview|null; readonly validations:readonly TimelineSyncValidation[]; readonly lastCommit:TimelineLinkGroupCommitResult|null; readonly conflicts:readonly TimelineLinkGroupConflict[]; }
