"""add broll runtime tables

Revision ID: 4d833d3102a6
Revises: 96097d1403c7
Create Date: 2026-07-04 14:45:18.292639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d833d3102a6'
down_revision: Union[str, Sequence[str], None] = '96097d1403c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
from app.db.types import GUID

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broll_plans',
    sa.Column('production_id', GUID(), nullable=False),
    sa.Column('timeline_id', GUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PROCESSING', 'COMPLETED', 'FAILED', name='brollstatus'), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], ),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broll_plans_production_id'), 'broll_plans', ['production_id'], unique=False)
    op.create_index(op.f('ix_broll_plans_status'), 'broll_plans', ['status'], unique=False)
    op.create_index(op.f('ix_broll_plans_timeline_id'), 'broll_plans', ['timeline_id'], unique=False)
    op.create_table('broll_cues',
    sa.Column('broll_plan_id', GUID(), nullable=False),
    sa.Column('asset_id', GUID(), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('source_type', sa.Enum('SUGGESTION', 'STOCK', 'GENERATED', 'UPLOADED', name='brollsourcetype'), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('keyword', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['broll_plan_id'], ['broll_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broll_cues_asset_id'), 'broll_cues', ['asset_id'], unique=False)
    op.create_index(op.f('ix_broll_cues_broll_plan_id'), 'broll_cues', ['broll_plan_id'], unique=False)
    op.create_index(op.f('ix_broll_cues_source_type'), 'broll_cues', ['source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_broll_cues_source_type'), table_name='broll_cues')
    op.drop_index(op.f('ix_broll_cues_broll_plan_id'), table_name='broll_cues')
    op.drop_index(op.f('ix_broll_cues_asset_id'), table_name='broll_cues')
    op.drop_table('broll_cues')
    op.drop_index(op.f('ix_broll_plans_timeline_id'), table_name='broll_plans')
    op.drop_index(op.f('ix_broll_plans_status'), table_name='broll_plans')
    op.drop_index(op.f('ix_broll_plans_production_id'), table_name='broll_plans')
    op.drop_table('broll_plans')
    # ### end Alembic commands ###
