"""add render runtime tables

Revision ID: 54b3ba688ee2
Revises: 6036f9be5b88
Create Date: 2026-07-04 16:19:03.954982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.types import GUID

# revision identifiers, used by Alembic.
revision: str = '54b3ba688ee2'
down_revision: Union[str, Sequence[str], None] = '6036f9be5b88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('render_plans',
    sa.Column('production_id', GUID(), nullable=False),
    sa.Column('timeline_id', GUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PROCESSING', 'COMPLETED', 'FAILED', name='renderplanstatus'), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('resolution', sa.String(), nullable=False),
    sa.Column('fps', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], ),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_render_plans_production_id'), 'render_plans', ['production_id'], unique=False)
    op.create_index(op.f('ix_render_plans_status'), 'render_plans', ['status'], unique=False)
    op.create_index(op.f('ix_render_plans_timeline_id'), 'render_plans', ['timeline_id'], unique=False)
    op.create_table('render_tracks',
    sa.Column('render_plan_id', GUID(), nullable=False),
    sa.Column('type', sa.Enum('VIDEO', 'SUBTITLE', 'BROLL', 'SOUND_EFFECT', 'MUSIC', 'EXPORT', name='rendertracktype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['render_plan_id'], ['render_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_render_tracks_render_plan_id'), 'render_tracks', ['render_plan_id'], unique=False)
    op.create_index(op.f('ix_render_tracks_type'), 'render_tracks', ['type'], unique=False)
    op.create_table('render_assets',
    sa.Column('render_track_id', GUID(), nullable=False),
    sa.Column('asset_id', GUID(), nullable=True),
    sa.Column('type', sa.Enum('SOURCE_VIDEO', 'SUBTITLE', 'BROLL', 'SOUND_EFFECT', 'MUSIC', 'GENERATED', name='renderassettype'), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('source_start', sa.Float(), nullable=True),
    sa.Column('source_end', sa.Float(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['render_track_id'], ['render_tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_render_assets_asset_id'), 'render_assets', ['asset_id'], unique=False)
    op.create_index(op.f('ix_render_assets_render_track_id'), 'render_assets', ['render_track_id'], unique=False)
    op.create_index(op.f('ix_render_assets_type'), 'render_assets', ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_render_assets_type'), table_name='render_assets')
    op.drop_index(op.f('ix_render_assets_render_track_id'), table_name='render_assets')
    op.drop_index(op.f('ix_render_assets_asset_id'), table_name='render_assets')
    op.drop_table('render_assets')
    op.drop_index(op.f('ix_render_tracks_type'), table_name='render_tracks')
    op.drop_index(op.f('ix_render_tracks_render_plan_id'), table_name='render_tracks')
    op.drop_table('render_tracks')
    op.drop_index(op.f('ix_render_plans_timeline_id'), table_name='render_plans')
    op.drop_index(op.f('ix_render_plans_status'), table_name='render_plans')
    op.drop_index(op.f('ix_render_plans_production_id'), table_name='render_plans')
    op.drop_table('render_plans')
    # ### end Alembic commands ###
