"""add music runtime tables

Revision ID: 6036f9be5b88
Revises: b90f352737ff
Create Date: 2026-07-04 15:53:02.383105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.types import GUID

# revision identifiers, used by Alembic.
revision: str = '6036f9be5b88'
down_revision: Union[str, Sequence[str], None] = 'b90f352737ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('music_plans',
    sa.Column('production_id', GUID(), nullable=False),
    sa.Column('timeline_id', GUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PROCESSING', 'COMPLETED', 'FAILED', name='musicstatus'), nullable=False),
    sa.Column('mood', sa.Enum('ENERGETIC', 'CALM', 'CINEMATIC', 'CORPORATE', 'INSPIRATIONAL', 'MINIMAL', 'CUSTOM', name='musicmood'), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], ),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_music_plans_mood'), 'music_plans', ['mood'], unique=False)
    op.create_index(op.f('ix_music_plans_production_id'), 'music_plans', ['production_id'], unique=False)
    op.create_index(op.f('ix_music_plans_status'), 'music_plans', ['status'], unique=False)
    op.create_index(op.f('ix_music_plans_timeline_id'), 'music_plans', ['timeline_id'], unique=False)
    op.create_table('music_cues',
    sa.Column('music_plan_id', GUID(), nullable=False),
    sa.Column('asset_id', GUID(), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('mood', sa.Enum('ENERGETIC', 'CALM', 'CINEMATIC', 'CORPORATE', 'INSPIRATIONAL', 'MINIMAL', 'CUSTOM', name='musicmood'), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('keyword', sa.String(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('fade_in', sa.Float(), nullable=False),
    sa.Column('fade_out', sa.Float(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['music_plan_id'], ['music_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_music_cues_asset_id'), 'music_cues', ['asset_id'], unique=False)
    op.create_index(op.f('ix_music_cues_mood'), 'music_cues', ['mood'], unique=False)
    op.create_index(op.f('ix_music_cues_music_plan_id'), 'music_cues', ['music_plan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_music_cues_music_plan_id'), table_name='music_cues')
    op.drop_index(op.f('ix_music_cues_mood'), table_name='music_cues')
    op.drop_index(op.f('ix_music_cues_asset_id'), table_name='music_cues')
    op.drop_table('music_cues')
    op.drop_index(op.f('ix_music_plans_timeline_id'), table_name='music_plans')
    op.drop_index(op.f('ix_music_plans_status'), table_name='music_plans')
    op.drop_index(op.f('ix_music_plans_production_id'), table_name='music_plans')
    op.drop_index(op.f('ix_music_plans_mood'), table_name='music_plans')
    op.drop_table('music_plans')
    # ### end Alembic commands ###
