"""add editing plans

Revision ID: 7aa223357a9b
Revises: 7ab37af0d8c2
Create Date: 2026-07-04 10:01:49.196045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.types import GUID

# revision identifiers, used by Alembic.
revision: str = '7aa223357a9b'
down_revision: Union[str, Sequence[str], None] = '7ab37af0d8c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('editing_plans',
    sa.Column('production_id', GUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PROCESSING', 'COMPLETED', 'FAILED', name='editingplanstatus'), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_editing_plans_production_id'), 'editing_plans', ['production_id'], unique=False)
    op.create_index(op.f('ix_editing_plans_status'), 'editing_plans', ['status'], unique=False)
    op.create_table('editing_plan_items',
    sa.Column('editing_plan_id', GUID(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('action', sa.Enum('KEEP', 'CUT', 'HOOK', 'HIGHLIGHT', 'BROLL', 'SOUND_EFFECT', 'SUBTITLE_EMPHASIS', name='editingplanitemaction'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['editing_plan_id'], ['editing_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_editing_plan_items_action'), 'editing_plan_items', ['action'], unique=False)
    op.create_index(op.f('ix_editing_plan_items_editing_plan_id'), 'editing_plan_items', ['editing_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_editing_plan_items_editing_plan_id'), table_name='editing_plan_items')
    op.drop_index(op.f('ix_editing_plan_items_action'), table_name='editing_plan_items')
    op.drop_table('editing_plan_items')
    op.drop_index(op.f('ix_editing_plans_status'), table_name='editing_plans')
    op.drop_index(op.f('ix_editing_plans_production_id'), table_name='editing_plans')
    op.drop_table('editing_plans')
    # ### end Alembic commands ###
