"""create current schema

Revision ID: 7ab37af0d8c2
Revises: 
Create Date: 2026-07-04 09:08:02.304778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.types

# revision identifiers, used by Alembic.
revision: str = '7ab37af0d8c2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('workspaces',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', app.db.types.GUID(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productions',
    sa.Column('workspace_id', app.db.types.GUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'UPLOADED', 'QUEUED', 'PROCESSING', 'REVIEW_READY', 'APPROVED', 'RENDERING', 'EXPORTED', 'FAILED', 'CANCELLED', name='productionstatus'), nullable=False),
    sa.Column('style', sa.String(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productions_status'), 'productions', ['status'], unique=False)
    op.create_table('assets',
    sa.Column('production_id', app.db.types.GUID(), nullable=False),
    sa.Column('type', sa.Enum('SOURCE_VIDEO', 'TRANSCRIPT', 'SUBTITLE', 'PREVIEW', 'EXPORT', name='assettype'), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_type'), 'assets', ['type'], unique=False)
    op.create_table('clips',
    sa.Column('production_id', app.db.types.GUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('start_seconds', sa.Float(), nullable=False),
    sa.Column('end_seconds', sa.Float(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SELECTED', 'REJECTED', 'APPROVED', 'FAILED', name='clipstatus'), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clips_status'), 'clips', ['status'], unique=False)
    op.create_table('exports',
    sa.Column('production_id', app.db.types.GUID(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RENDERING', 'COMPLETED', 'FAILED', 'EXPIRED', name='exportstatus'), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('storage_path', sa.String(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exports_status'), 'exports', ['status'], unique=False)
    op.create_table('queue_jobs',
    sa.Column('production_id', app.db.types.GUID(), nullable=False),
    sa.Column('type', sa.Enum('TRANSCRIPT', 'SUBTITLE', 'BROLL', 'MUSIC', 'THUMBNAIL', 'EXPORT', 'RENDER', name='queuetype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELED', name='queuestatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('worker_name', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queue_jobs_status'), 'queue_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_queue_jobs_type'), 'queue_jobs', ['type'], unique=False)
    op.create_table('render_jobs',
    sa.Column('production_id', app.db.types.GUID(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RENDERING', 'COMPLETED', 'FAILED', 'CANCELLED', name='renderjobstatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_render_jobs_status'), 'render_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_render_jobs_status'), table_name='render_jobs')
    op.drop_table('render_jobs')
    op.drop_index(op.f('ix_queue_jobs_type'), table_name='queue_jobs')
    op.drop_index(op.f('ix_queue_jobs_status'), table_name='queue_jobs')
    op.drop_table('queue_jobs')
    op.drop_index(op.f('ix_exports_status'), table_name='exports')
    op.drop_table('exports')
    op.drop_index(op.f('ix_clips_status'), table_name='clips')
    op.drop_table('clips')
    op.drop_index(op.f('ix_assets_type'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_productions_status'), table_name='productions')
    op.drop_table('productions')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
