"""add subtitle runtime tables

Revision ID: 96097d1403c7
Revises: af3b88939493
Create Date: 2026-07-04 13:55:35.557075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96097d1403c7'
down_revision: Union[str, Sequence[str], None] = 'af3b88939493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
from app.db.types import GUID

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subtitles',
    sa.Column('production_id', GUID(), nullable=False),
    sa.Column('timeline_id', GUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PROCESSING', 'COMPLETED', 'FAILED', name='subtitlestatus'), nullable=False),
    sa.Column('style', sa.Enum('DEFAULT', 'BOLD_KEYWORD', 'TIKTOK', 'MINIMAL', name='subtitlestyle'), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], ),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtitles_production_id'), 'subtitles', ['production_id'], unique=False)
    op.create_index(op.f('ix_subtitles_status'), 'subtitles', ['status'], unique=False)
    op.create_index(op.f('ix_subtitles_timeline_id'), 'subtitles', ['timeline_id'], unique=False)
    op.create_table('subtitle_cues',
    sa.Column('subtitle_id', GUID(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('style_json', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subtitle_id'], ['subtitles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtitle_cues_subtitle_id'), 'subtitle_cues', ['subtitle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_subtitle_cues_subtitle_id'), table_name='subtitle_cues')
    op.drop_table('subtitle_cues')
    op.drop_index(op.f('ix_subtitles_timeline_id'), table_name='subtitles')
    op.drop_index(op.f('ix_subtitles_status'), table_name='subtitles')
    op.drop_index(op.f('ix_subtitles_production_id'), table_name='subtitles')
    op.drop_table('subtitles')
    # ### end Alembic commands ###
