"""add timeline tables

Revision ID: af3b88939493
Revises: 43e25f48b634
Create Date: 2026-07-04 11:48:54.245706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af3b88939493'
down_revision: Union[str, Sequence[str], None] = '43e25f48b634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
from app.db.types import GUID

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timelines',
    sa.Column('production_id', GUID(), nullable=False),
    sa.Column('editing_plan_id', GUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PROCESSING', 'COMPLETED', 'FAILED', name='timelinestatus'), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['editing_plan_id'], ['editing_plans.id'], ),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timelines_editing_plan_id'), 'timelines', ['editing_plan_id'], unique=False)
    op.create_index(op.f('ix_timelines_production_id'), 'timelines', ['production_id'], unique=False)
    op.create_index(op.f('ix_timelines_status'), 'timelines', ['status'], unique=False)
    op.create_table('timeline_tracks',
    sa.Column('timeline_id', GUID(), nullable=False),
    sa.Column('type', sa.Enum('VIDEO', 'AUDIO', 'SUBTITLE', 'BROLL', 'SOUND_EFFECT', 'MUSIC', name='timelinetracktype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_tracks_timeline_id'), 'timeline_tracks', ['timeline_id'], unique=False)
    op.create_index(op.f('ix_timeline_tracks_type'), 'timeline_tracks', ['type'], unique=False)
    op.create_table('timeline_clips',
    sa.Column('track_id', GUID(), nullable=False),
    sa.Column('asset_id', GUID(), nullable=True),
    sa.Column('source_start', sa.Float(), nullable=True),
    sa.Column('source_end', sa.Float(), nullable=True),
    sa.Column('timeline_start', sa.Float(), nullable=False),
    sa.Column('timeline_end', sa.Float(), nullable=False),
    sa.Column('type', sa.Enum('SOURCE', 'GENERATED', 'SUBTITLE', 'BROLL', 'SOUND_EFFECT', 'MUSIC', name='timelinecliptype'), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['timeline_tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_clips_asset_id'), 'timeline_clips', ['asset_id'], unique=False)
    op.create_index(op.f('ix_timeline_clips_track_id'), 'timeline_clips', ['track_id'], unique=False)
    op.create_index(op.f('ix_timeline_clips_type'), 'timeline_clips', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeline_clips_type'), table_name='timeline_clips')
    op.drop_index(op.f('ix_timeline_clips_track_id'), table_name='timeline_clips')
    op.drop_index(op.f('ix_timeline_clips_asset_id'), table_name='timeline_clips')
    op.drop_table('timeline_clips')
    op.drop_index(op.f('ix_timeline_tracks_type'), table_name='timeline_tracks')
    op.drop_index(op.f('ix_timeline_tracks_timeline_id'), table_name='timeline_tracks')
    op.drop_table('timeline_tracks')
    op.drop_index(op.f('ix_timelines_status'), table_name='timelines')
    op.drop_index(op.f('ix_timelines_production_id'), table_name='timelines')
    op.drop_index(op.f('ix_timelines_editing_plan_id'), table_name='timelines')
    op.drop_table('timelines')
    # ### end Alembic commands ###
