"""add sound effect runtime tables

Revision ID: b90f352737ff
Revises: 4d833d3102a6
Create Date: 2026-07-04 15:31:10.165487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.types import GUID

# revision identifiers, used by Alembic.
revision: str = 'b90f352737ff'
down_revision: Union[str, Sequence[str], None] = '4d833d3102a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sound_effect_plans',
    sa.Column('production_id', GUID(), nullable=False),
    sa.Column('timeline_id', GUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PROCESSING', 'COMPLETED', 'FAILED', name='soundeffectstatus'), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], ),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sound_effect_plans_production_id'), 'sound_effect_plans', ['production_id'], unique=False)
    op.create_index(op.f('ix_sound_effect_plans_status'), 'sound_effect_plans', ['status'], unique=False)
    op.create_index(op.f('ix_sound_effect_plans_timeline_id'), 'sound_effect_plans', ['timeline_id'], unique=False)
    op.create_table('sound_effect_cues',
    sa.Column('sound_effect_plan_id', GUID(), nullable=False),
    sa.Column('asset_id', GUID(), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('effect_type', sa.Enum('WHOOSH', 'POP', 'CLICK', 'TRANSITION', 'IMPACT', 'AMBIENT', 'CUSTOM', name='soundeffecttype'), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('keyword', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['sound_effect_plan_id'], ['sound_effect_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sound_effect_cues_asset_id'), 'sound_effect_cues', ['asset_id'], unique=False)
    op.create_index(op.f('ix_sound_effect_cues_effect_type'), 'sound_effect_cues', ['effect_type'], unique=False)
    op.create_index(op.f('ix_sound_effect_cues_sound_effect_plan_id'), 'sound_effect_cues', ['sound_effect_plan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_sound_effect_cues_sound_effect_plan_id'), table_name='sound_effect_cues')
    op.drop_index(op.f('ix_sound_effect_cues_effect_type'), table_name='sound_effect_cues')
    op.drop_index(op.f('ix_sound_effect_cues_asset_id'), table_name='sound_effect_cues')
    op.drop_table('sound_effect_cues')
    op.drop_index(op.f('ix_sound_effect_plans_timeline_id'), table_name='sound_effect_plans')
    op.drop_index(op.f('ix_sound_effect_plans_status'), table_name='sound_effect_plans')
    op.drop_index(op.f('ix_sound_effect_plans_production_id'), table_name='sound_effect_plans')
    op.drop_table('sound_effect_plans')
    # ### end Alembic commands ###
