"""add content understanding tables

Revision ID: dabff647fbf1
Revises: 54b3ba688ee2
Create Date: 2026-07-06 08:27:35.449941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.types import GUID

# revision identifiers, used by Alembic.
revision: str = 'dabff647fbf1'
down_revision: Union[str, Sequence[str], None] = '54b3ba688ee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_graphs',
    sa.Column('production_id', GUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PROCESSING', 'COMPLETED', 'FAILED', name='contentgraphstatus'), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('topic_json', sa.Text(), nullable=True),
    sa.Column('speaker_json', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_graphs_production_id'), 'content_graphs', ['production_id'], unique=False)
    op.create_index(op.f('ix_content_graphs_status'), 'content_graphs', ['status'], unique=False)
    op.create_table('content_segments',
    sa.Column('content_graph_id', GUID(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('type', sa.Enum('INTRO', 'HOOK', 'MAIN_POINT', 'EXAMPLE', 'STORY', 'CTA', 'FILLER', 'UNKNOWN', name='contentsegmenttype'), nullable=False),
    sa.Column('emotion', sa.Enum('NEUTRAL', 'EXCITED', 'SURPRISED', 'SERIOUS', 'FUNNY', 'INSPIRATIONAL', 'CONFUSED', 'ANGRY', name='contentemotion'), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('viral_potential_score', sa.Float(), nullable=False),
    sa.Column('speaker_id', sa.String(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_graph_id'], ['content_graphs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_segments_content_graph_id'), 'content_segments', ['content_graph_id'], unique=False)
    op.create_index(op.f('ix_content_segments_emotion'), 'content_segments', ['emotion'], unique=False)
    op.create_index(op.f('ix_content_segments_type'), 'content_segments', ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_segments_type'), table_name='content_segments')
    op.drop_index(op.f('ix_content_segments_emotion'), table_name='content_segments')
    op.drop_index(op.f('ix_content_segments_content_graph_id'), table_name='content_segments')
    op.drop_table('content_segments')
    op.drop_index(op.f('ix_content_graphs_status'), table_name='content_graphs')
    op.drop_index(op.f('ix_content_graphs_production_id'), table_name='content_graphs')
    op.drop_table('content_graphs')
    # ### end Alembic commands ###
