from app.speech.base import (
    SpeechProvider,
    TranscriptResult,
    TranscriptSegmentResult,
)


class GeminiSpeechProvider(SpeechProvider):
    def transcribe(self, file_path: str) -> TranscriptResult:
        # TODO: Implement real Gemini audio/video transcription later.
        return TranscriptResult(
            language="vi",
            duration=None,
            provider="gemini",
            text="Mock transcript generated by Gemini provider.",
            segments=[
                TranscriptSegmentResult(
                    start_time=0.0,
                    end_time=3.0,
                    text="Mock transcript generated by Gemini provider.",
                    speaker=None,
                    confidence=0.9,
                )
            ],
        )