from app.speech.base import (
    SpeechProvider,
    TranscriptResult,
    TranscriptSegmentResult,
)


class WhisperSpeechProvider(SpeechProvider):
    def transcribe(self, file_path: str) -> TranscriptResult:
        # TODO: Implement real Whisper integration in Sprint 7.1.4+
        return TranscriptResult(
            language="vi",
            duration=None,
            provider="whisper",
            text="Mock transcript generated by Whisper provider.",
            segments=[
                TranscriptSegmentResult(
                    start_time=0.0,
                    end_time=3.0,
                    text="Mock transcript generated by Whisper provider.",
                    speaker=None,
                    confidence=0.9,
                )
            ],
        )