import { TIMELINE_LINK_GROUP_SYNC_CONTRACT_VERSION, type BeginTimelineLinkGroupRequest, type LinkableTimelineClip, type TimelineLinkGroup, type TimelineLinkGroupChangeSet, type TimelineLinkGroupCommitResult, type TimelineLinkGroupConflict, type TimelineLinkGroupOperationPreview, type TimelineLinkGroupSyncConfiguration, type TimelineLinkGroupSyncSession, type TimelineLinkGroupSyncSnapshot, type TimelineLinkGroupSyncStatus, type TimelineLinkMembership, type TimelineSyncRelation, type TimelineSyncRepairPreview, type TimelineSyncRepairRequest, type TimelineSyncValidation } from "../contracts/link-group-sync-contracts";
import { LinkGroupMembershipModel } from "./link-group-membership-model";
import { SyncRelationModel } from "./sync-relation-model";
import { SynchronizationRepairModel } from "./synchronization-repair-model";

type Listener=(snapshot:TimelineLinkGroupSyncSnapshot,event:string)=>void;
const freeze=<T>(value:T):T=>Object.freeze(value);
const emptyChangeSet=():TimelineLinkGroupChangeSet=>freeze({createdGroups:freeze([]),updatedGroups:freeze([]),removedGroupIds:freeze([]),createdRelations:freeze([]),updatedRelations:freeze([]),removedRelationIds:freeze([]),membershipsAdded:freeze([]),membershipsRemoved:freeze([]),repairChanges:freeze([])});

export class TimelineLinkGroupSyncRuntime {
  private configuration:Required<TimelineLinkGroupSyncConfiguration>|null=null;
  private clips:readonly LinkableTimelineClip[]=freeze([]); private groups:readonly TimelineLinkGroup[]=freeze([]); private relations:readonly TimelineSyncRelation[]=freeze([]); private memberships:readonly TimelineLinkMembership[]=freeze([]);
  private status:TimelineLinkGroupSyncStatus="idle"; private version=0; private session:TimelineLinkGroupSyncSession|null=null; private preview:TimelineLinkGroupOperationPreview|null=null; private repairPreview:TimelineSyncRepairPreview|null=null; private validations:readonly TimelineSyncValidation[]=freeze([]); private conflicts:readonly TimelineLinkGroupConflict[]=freeze([]); private lastCommit:TimelineLinkGroupCommitResult|null=null; private listeners=new Set<Listener>();

  configure(c:TimelineLinkGroupSyncConfiguration){this.assertUsable(); if(!Number.isFinite(c.framesPerSecond)||c.framesPerSecond<=0) throw new Error("invalid-frames-per-second"); const n=freeze({framesPerSecond:c.framesPerSecond,defaultToleranceFrames:c.defaultToleranceFrames??1,defaultSyncMode:c.defaultSyncMode??"start",allowSingleMemberGroup:c.allowSingleMemberGroup??false,dissolveSingleMemberGroup:c.dissolveSingleMemberGroup??true,preserveStartOffsets:c.preserveStartOffsets??true,preserveEndOffsets:c.preserveEndOffsets??false,preserveSourceOffsets:c.preserveSourceOffsets??false,autoIncludeExistingGroupMembers:c.autoIncludeExistingGroupMembers??true,autoSelectAnchor:c.autoSelectAnchor??true,autoRepairWithinTolerance:c.autoRepairWithinTolerance??true,blockLockedClipChanges:c.blockLockedClipChanges??true,blockLockedGroupChanges:c.blockLockedGroupChanges??true,clampRepairToTimelineStart:c.clampRepairToTimelineStart??true,timelineStartFrame:c.timelineStartFrame??0,timelineEndFrame:c.timelineEndFrame??null}); if(JSON.stringify(this.configuration)===JSON.stringify(n))return; this.configuration=n; this.emit("configured");}

  loadRegistry(input:{clips:readonly LinkableTimelineClip[];groups:readonly TimelineLinkGroup[];relations?:readonly TimelineSyncRelation[]}){this.assertUsable(); this.validateRegistry(input.clips,input.groups,input.relations??[]); this.clips=freeze(input.clips.map(c=>freeze({...c})).sort((a,b)=>a.timelineStartFrame-b.timelineStartFrame||a.clipId.localeCompare(b.clipId))); this.groups=freeze(input.groups.map(g=>freeze({...g,clipIds:freeze([...new Set(g.clipIds)]),createdFromGroupIds:freeze([...g.createdFromGroupIds])})).sort((a,b)=>a.groupId.localeCompare(b.groupId))); this.relations=freeze((input.relations??[]).map(r=>freeze({...r})).sort((a,b)=>a.groupId.localeCompare(b.groupId)||a.linkedClipId.localeCompare(b.linkedClipId))); this.memberships=LinkGroupMembershipModel.build(this.clips,this.groups); this.emit("registry_loaded");}

  beginOperation(r:BeginTimelineLinkGroupRequest){this.assertUsable(); if(this.session)return; if(!r.sessionId) return this.block("missing-session-id","Session id is required"); this.loadRegistry({clips:r.clips,groups:r.groups,relations:r.relations}); const selectedClipIds=freeze([...new Set(r.selectedClipIds??[])]); const selectedGroupIds=freeze([...new Set(r.selectedGroupIds??[])]); const anchor=this.resolveAnchor(r.requestedAnchorClipId??null,selectedClipIds); this.session=freeze({sessionId:r.sessionId,operation:r.operation,selectedClipIds,selectedGroupIds,targetGroupId:r.targetGroupId??null,anchorClipId:anchor,startedAtVersion:this.version}); (this.session as any).splitPlan=r.splitPlan??null; (this.session as any).relinkPlan=r.relinkPlan??null; this.status="editing"; this.emit("operation_started");}

  previewCreateGroup(){const s=this.needSession("create-group"); if(!s.targetGroupId)return this.blockPreview("missing-target-group-id","Target group id is required"); if(s.selectedClipIds.length<2)return this.blockPreview("insufficient-group-members","At least two clips are required"); const anchor=s.anchorClipId??this.resolveAnchor(null,s.selectedClipIds); if(!anchor)return this.blockPreview("missing-anchor","Anchor is required"); const group=freeze({groupId:s.targetGroupId,anchorClipId:anchor,clipIds:freeze([...s.selectedClipIds].sort()),createdFromGroupIds:freeze([]),syncEnabled:true,locked:false,version:1}); const rels=SyncRelationModel.capture(group,this.clips,this.cfg.defaultSyncMode,this.cfg.defaultToleranceFrames); return this.setPreview({createdGroups:[group],createdRelations:rels},"group_create_previewed");}
  previewAddMembers(){const s=this.needSession("add-members"); const g=this.group(s.targetGroupId??s.selectedGroupIds[0]); if(!g)return this.blockPreview("unknown-group","Group not found"); const ids=freeze([...new Set([...g.clipIds,...s.selectedClipIds])].sort()); const updated=freeze({...g,clipIds:ids,version:g.version+1}); const rels=SyncRelationModel.capture(updated,this.clips,this.cfg.defaultSyncMode,this.cfg.defaultToleranceFrames); return this.setPreview({updatedGroups:[updated],createdRelations:rels,removedRelationIds:this.relations.filter(r=>r.groupId===g.groupId).map(r=>r.relationId)},"members_add_previewed");}
  previewRemoveMembers(){const s=this.needSession("remove-members"); const g=this.group(s.targetGroupId??s.selectedGroupIds[0]); if(!g)return this.blockPreview("unknown-group","Group not found"); const remain=g.clipIds.filter(id=>!s.selectedClipIds.includes(id)); if(remain.length<2&&this.cfg.dissolveSingleMemberGroup)return this.setPreview({removedGroupIds:[g.groupId],removedRelationIds:this.relations.filter(r=>r.groupId===g.groupId).map(r=>r.relationId),membershipsRemoved:this.memberships.filter(m=>m.groupId===g.groupId)},"members_remove_previewed"); const anchor=remain.includes(g.anchorClipId)?g.anchorClipId:this.resolveAnchor(null,remain); if(!anchor)return this.blockPreview("missing-anchor","Anchor is required"); const updated=freeze({...g,anchorClipId:anchor,clipIds:freeze(remain),version:g.version+1}); return this.setPreview({updatedGroups:[updated],createdRelations:SyncRelationModel.capture(updated,this.clips,this.cfg.defaultSyncMode,this.cfg.defaultToleranceFrames),removedRelationIds:this.relations.filter(r=>r.groupId===g.groupId).map(r=>r.relationId)},"members_remove_previewed");}
  previewMergeGroups(){const s=this.needSession("merge-groups"); if(!s.targetGroupId)return this.blockPreview("missing-target-group-id","Target group id is required"); const sources=s.selectedGroupIds.map(id=>this.group(id)).filter(Boolean) as TimelineLinkGroup[]; if(sources.length<2)return this.blockPreview("missing-selection","Select at least two groups"); const ids=freeze([...new Set(sources.flatMap(g=>g.clipIds))].sort()); const anchor=s.anchorClipId??this.resolveAnchor(null,ids); if(!anchor)return this.blockPreview("missing-anchor","Anchor is required"); const merged=freeze({groupId:s.targetGroupId,anchorClipId:anchor,clipIds:ids,createdFromGroupIds:freeze(sources.map(g=>g.groupId).sort()),syncEnabled:true,locked:false,version:1}); return this.setPreview({createdGroups:[merged],removedGroupIds:sources.map(g=>g.groupId),createdRelations:SyncRelationModel.capture(merged,this.clips,this.cfg.defaultSyncMode,this.cfg.defaultToleranceFrames),removedRelationIds:this.relations.filter(r=>sources.some(g=>g.groupId===r.groupId)).map(r=>r.relationId)},"groups_merge_previewed");}
  previewSplitGroup(){const s=this.needSession("split-group"); const plan=(s as any).splitPlan; if(!plan)return this.blockPreview("invalid-split-plan","Split plan is required"); const source=this.group(plan.sourceGroupId); if(!source)return this.blockPreview("unknown-group","Source group not found"); const seen=new Set<string>(); const created:TimelineLinkGroup[]=[]; const rels:TimelineSyncRelation[]=[]; for(const p of plan.partitions){for(const id of p.clipIds){if(seen.has(id))return this.blockPreview("split-partition-overlap","Clip appears in multiple partitions");seen.add(id);} const anchor=p.anchorClipId??this.resolveAnchor(null,p.clipIds); if(!anchor)return this.blockPreview("missing-anchor","Partition anchor required"); const g=freeze({groupId:p.targetGroupId,anchorClipId:anchor,clipIds:freeze([...p.clipIds]),createdFromGroupIds:freeze([source.groupId]),syncEnabled:true,locked:false,version:1}); created.push(g); rels.push(...SyncRelationModel.capture(g,this.clips,this.cfg.defaultSyncMode,this.cfg.defaultToleranceFrames));} return this.setPreview({createdGroups:created,removedGroupIds:[source.groupId],createdRelations:rels,removedRelationIds:this.relations.filter(r=>r.groupId===source.groupId).map(r=>r.relationId)},"group_split_previewed");}
  previewUnlinkGroup(){const s=this.needSession("unlink-group"); const id=s.targetGroupId??s.selectedGroupIds[0]; const g=this.group(id); if(!g)return this.blockPreview("unknown-group","Group not found"); return this.setPreview({removedGroupIds:[g.groupId],removedRelationIds:this.relations.filter(r=>r.groupId===g.groupId).map(r=>r.relationId),membershipsRemoved:this.memberships.filter(m=>m.groupId===g.groupId)},"group_unlink_previewed");}
  previewChangeAnchor(){const s=this.needSession("change-anchor"); const g=this.group(s.targetGroupId??s.selectedGroupIds[0]); if(!g)return this.blockPreview("unknown-group","Group not found"); if(!s.anchorClipId||!g.clipIds.includes(s.anchorClipId))return this.blockPreview("anchor-not-in-group","Anchor must belong to group"); const updated=freeze({...g,anchorClipId:s.anchorClipId,version:g.version+1}); return this.setPreview({updatedGroups:[updated],createdRelations:SyncRelationModel.capture(updated,this.clips,this.cfg.defaultSyncMode,this.cfg.defaultToleranceFrames),removedRelationIds:this.relations.filter(r=>r.groupId===g.groupId).map(r=>r.relationId)},"anchor_change_previewed");}
  previewCaptureSync(){const s=this.needSession("capture-sync"); const g=this.group(s.targetGroupId??s.selectedGroupIds[0]); if(!g)return this.blockPreview("unknown-group","Group not found"); return this.setPreview({createdRelations:SyncRelationModel.capture(g,this.clips,this.cfg.defaultSyncMode,this.cfg.defaultToleranceFrames),removedRelationIds:this.relations.filter(r=>r.groupId===g.groupId).map(r=>r.relationId)},"sync_captured");}
  validateGroupSync(groupId:string){this.status="validating"; this.validations=freeze(this.relations.filter(r=>r.groupId===groupId).map(r=>SyncRelationModel.validate(r,this.clips))); this.emit(this.validations.some(v=>v.state==="out-of-sync")?"sync_drift_detected":"sync_validated"); return this.validations;}
  validateAllSync(){this.status="validating"; this.validations=freeze(this.relations.map(r=>SyncRelationModel.validate(r,this.clips))); this.emit("sync_validated"); return this.validations;}
  previewRepairSync(req:TimelineSyncRepairRequest){this.assertUsable(); const rels=this.relations.filter(r=>r.groupId===req.groupId&&(!req.relationIds||req.relationIds.includes(r.relationId))); const before=freeze(rels.map(r=>SyncRelationModel.validate(r,this.clips))); const changes=SynchronizationRepairModel.build(this.clips,rels,req.strategy); const repairedClips=this.clips.map(c=>{const ch=changes.find(x=>x.clipId===c.clipId);return ch?freeze({...c,timelineStartFrame:ch.previewStartFrame,timelineEndFrame:ch.previewEndFrame}):c;}); const after=freeze(rels.map(r=>SyncRelationModel.validate(r,repairedClips))); const unresolved=freeze(after.filter(v=>v.state==="out-of-sync").map(v=>v.relationId)); this.repairPreview=freeze({groupId:req.groupId,strategy:req.strategy,changes,validationsBefore:before,validationsAfter:after,repairedRelationIds:freeze(after.filter(v=>v.state!=="out-of-sync").map(v=>v.relationId)),unresolvedRelationIds:unresolved,clamped:false,blocked:unresolved.length>0&&req.strategy!=="ignore",conflicts:freeze(unresolved.map(id=>freeze({code:"repair-unresolved",message:"Repair unresolved",relationId:id,blocking:true}))) }); this.status=this.repairPreview.blocked?"blocked":"repairing"; this.emit("sync_repair_previewed"); return this.repairPreview;}
  previewRelinkAfterSplit(){this.needSession("relink-after-split"); return this.setPreview({},"relink_previewed");}
  commitOperation(){this.assertUsable(); if(!this.session||!this.preview||this.preview.blocked)return null; if(this.lastCommit?.sessionId===this.session.sessionId)return this.lastCommit; const result=freeze({sessionId:this.session.sessionId,operation:this.session.operation,committed:true,changeSet:this.preview.changeSet,resultingGroups:this.preview.resultingGroups,resultingRelations:this.preview.resultingRelations,resultingMemberships:this.preview.resultingMemberships,conflicts:this.preview.conflicts}); this.lastCommit=result; this.groups=result.resultingGroups; this.relations=result.resultingRelations; this.memberships=result.resultingMemberships; this.status="committed"; this.emit("operation_committed"); return result;}
  cancelOperation(){if(!this.session)return; this.session=null;this.preview=null;this.repairPreview=null;this.status="cancelled";this.emit("operation_cancelled");}
  subscribe(l:Listener){this.listeners.add(l);return()=>this.listeners.delete(l);}
  getSnapshot():TimelineLinkGroupSyncSnapshot{return freeze({contractVersion:TIMELINE_LINK_GROUP_SYNC_CONTRACT_VERSION,version:this.version,status:this.status,configured:!!this.configuration,clips:this.clips,groups:this.groups,relations:this.relations,memberships:this.memberships,session:this.session,preview:this.preview,repairPreview:this.repairPreview,validations:this.validations,lastCommit:this.lastCommit,conflicts:this.conflicts});}
  reset(){this.assertUsable();this.clips=freeze([]);this.groups=freeze([]);this.relations=freeze([]);this.memberships=freeze([]);this.session=null;this.preview=null;this.repairPreview=null;this.validations=freeze([]);this.conflicts=freeze([]);this.lastCommit=null;this.status="idle";this.emit("reset");}
  dispose(){this.status="disposed";this.listeners.clear();}

  private get cfg(){if(!this.configuration)throw new Error("Runtime not configured");return this.configuration;}
  private assertUsable(){if(this.status==="disposed")throw new Error("Runtime disposed");}
  private emit(event:string){this.version++;const s=this.getSnapshot();for(const l of this.listeners)l(s,event);}
  private group(id:string|undefined|null){return id?this.groups.find(g=>g.groupId===id):undefined;}
  private resolveAnchor(requested:string|null,ids:readonly string[]){if(requested&&ids.includes(requested))return requested; const clips=ids.map(id=>this.clips.find(c=>c.clipId===id)).filter(Boolean) as LinkableTimelineClip[]; return [...clips].sort((a,b)=>Number(b.kind==="video")-Number(a.kind==="video")||Number(b.kind==="audio")-Number(a.kind==="audio")||a.timelineStartFrame-b.timelineStartFrame||a.trackId.localeCompare(b.trackId)||a.clipId.localeCompare(b.clipId))[0]?.clipId??null;}
  private needSession(op:string){this.assertUsable(); if(!this.session||this.session.operation!==op)throw new Error(`Expected ${op} session`); return this.session;}
  private block(code:any,message:string){this.conflicts=freeze([freeze({code,message,blocking:true})]);this.status="blocked";this.emit("operation_blocked");return null;}
  private blockPreview(code:any,message:string){this.conflicts=freeze([freeze({code,message,blocking:true})]); const p=freeze({operation:this.session!.operation,changeSet:emptyChangeSet(),resultingGroups:this.groups,resultingRelations:this.relations,resultingMemberships:this.memberships,syncValidations:freeze([]),conflicts:this.conflicts,blocked:true});this.preview=p;this.status="blocked";this.emit("operation_blocked");return p;}
  private setPreview(partial:Partial<TimelineLinkGroupChangeSet>,event:string){const cs=freeze({...emptyChangeSet(),...partial,createdGroups:freeze([...(partial.createdGroups??[])]),updatedGroups:freeze([...(partial.updatedGroups??[])]),removedGroupIds:freeze([...(partial.removedGroupIds??[])]),createdRelations:freeze([...(partial.createdRelations??[])]),updatedRelations:freeze([...(partial.updatedRelations??[])]),removedRelationIds:freeze([...(partial.removedRelationIds??[])]),membershipsAdded:freeze([...(partial.membershipsAdded??[])]),membershipsRemoved:freeze([...(partial.membershipsRemoved??[])]),repairChanges:freeze([...(partial.repairChanges??[])])}); const removed=new Set(cs.removedGroupIds); const updated=new Map(cs.updatedGroups.map(g=>[g.groupId,g])); const resultingGroups=freeze([...this.groups.filter(g=>!removed.has(g.groupId)).map(g=>updated.get(g.groupId)??g),...cs.createdGroups].sort((a,b)=>a.groupId.localeCompare(b.groupId))); const removedR=new Set(cs.removedRelationIds); const resultingRelations=freeze([...this.relations.filter(r=>!removedR.has(r.relationId)),...cs.updatedRelations,...cs.createdRelations].sort((a,b)=>a.groupId.localeCompare(b.groupId)||a.linkedClipId.localeCompare(b.linkedClipId))); const memberships=LinkGroupMembershipModel.build(this.clips,resultingGroups); this.preview=freeze({operation:this.session!.operation,changeSet:cs,resultingGroups,resultingRelations,resultingMemberships:memberships,syncValidations:freeze(resultingRelations.map(r=>SyncRelationModel.validate(r,this.clips))),conflicts:freeze([]),blocked:false}); this.status="previewing";this.emit(event);return this.preview;}
  private validateRegistry(clips:readonly LinkableTimelineClip[],groups:readonly TimelineLinkGroup[],relations:readonly TimelineSyncRelation[]){const c=new Set<string>(),g=new Set<string>(),r=new Set<string>();for(const x of clips){if(c.has(x.clipId))throw new Error("duplicate-clip-id");c.add(x.clipId);if(x.timelineEndFrame<=x.timelineStartFrame)throw new Error("invalid-timeline-range");}for(const x of groups){if(g.has(x.groupId))throw new Error("duplicate-group-id");g.add(x.groupId);if(!x.clipIds.includes(x.anchorClipId))throw new Error("anchor-not-in-group");}for(const x of relations){if(r.has(x.relationId))throw new Error("duplicate-relation-id");r.add(x.relationId);if(x.toleranceFrames<0)throw new Error("invalid-tolerance");}}
}
