export const TIMELINE_MULTI_TRACK_EDIT_CONTRACT_VERSION = "16.8.8.4" as const;

export type MultiTrackKind = "video" | "audio" | "subtitle" | "overlay" | "effect" | "custom";
export type MultiTrackEditOperation = "move" | "ripple-move" | "ripple-insert" | "ripple-delete" | "linked-trim-start" | "linked-trim-end";
export type TimelineMultiTrackEditStatus = "idle" | "editing" | "previewing" | "blocked" | "committed" | "cancelled" | "disposed";
export type TimelineMultiTrackEditEventType = "configured" | "snap_resolver_set" | "snap_resolver_cleared" | "edit_started" | "preview_updated" | "snap_applied" | "collision_detected" | "sync_violation_detected" | "edit_blocked" | "edit_committed" | "edit_cancelled" | "reset" | "disposed";

export interface MultiTrackDescriptor { readonly trackId:string; readonly kind:MultiTrackKind; readonly order:number; readonly locked?:boolean; readonly rippleEnabled?:boolean; readonly syncEnabled?:boolean; }
export interface MultiTrackTimelineClip { readonly clipId:string; readonly trackId:string; readonly timelineStartFrame:number; readonly timelineEndFrame:number; readonly sourceStartFrame?:number|null; readonly sourceEndFrame?:number|null; readonly sourceDurationFrames?:number|null; readonly linkGroupId?:string|null; readonly syncOffsetFrames?:number; readonly locked?:boolean; readonly enabled?:boolean; }
export interface TimelineMultiTrackEditConfiguration { readonly framesPerSecond:number; readonly timelineStartFrame?:number; readonly timelineEndFrame?:number|null; readonly minimumClipDurationFrames?:number; readonly preserveLinkGroups?:boolean; readonly preserveSyncOffsets?:boolean; readonly includeLinkedClipsByDefault?:boolean; readonly includeRippleEnabledTracksByDefault?:boolean; readonly blockOnLockedTrack?:boolean; readonly blockOnLockedClip?:boolean; readonly blockOnCollision?:boolean; readonly clampPreviewToTimelineBounds?:boolean; readonly magneticSnapEnabled?:boolean; }
export interface MultiTrackLinkGroup { readonly linkGroupId:string; readonly clipIds:readonly string[]; readonly anchorClipId:string; readonly minimumStartFrame:number; readonly maximumEndFrame:number; }
export interface MultiTrackSyncRelation { readonly anchorClipId:string; readonly linkedClipId:string; readonly offsetFrames:number; }
export interface MultiTrackDeleteRange { readonly startFrame:number; readonly endFrame:number; }
export interface BeginTimelineMultiTrackEditRequest { readonly sessionId:string; readonly operation:MultiTrackEditOperation; readonly tracks:readonly MultiTrackDescriptor[]; readonly clips:readonly MultiTrackTimelineClip[]; readonly selectedClipIds:readonly string[]; readonly anchorClipId?:string|null; readonly pivotFrame?:number|null; readonly includeLinkedClips?:boolean; readonly affectedTrackIds?:readonly string[]|null; }
export interface TimelineMultiTrackEditSession { readonly sessionId:string; readonly operation:MultiTrackEditOperation; readonly anchorClipId:string; readonly selectedClipIds:readonly string[]; readonly affectedClipIds:readonly string[]; readonly affectedTrackIds:readonly string[]; readonly pivotFrame:number; readonly startedAtVersion:number; }
export interface MultiTrackClipPosition { readonly clipId:string; readonly trackId:string; readonly timelineStartFrame:number; readonly timelineEndFrame:number; readonly sourceStartFrame:number|null; readonly sourceEndFrame:number|null; }
export type MultiTrackChangeKind = "moved" | "trimmed-start" | "trimmed-end" | "ripple-shifted" | "unchanged" | "deleted";
export interface MultiTrackClipChange { readonly clipId:string; readonly trackId:string; readonly kind:MultiTrackChangeKind; readonly original:MultiTrackClipPosition; readonly preview:MultiTrackClipPosition; readonly deltaFrames:number; }
export type MultiTrackCollisionKind = "overlap" | "timeline-underflow" | "timeline-overflow" | "minimum-duration" | "pivot-intersects-clip";
export interface MultiTrackCollision { readonly kind:MultiTrackCollisionKind; readonly trackId:string; readonly clipId:string; readonly conflictingClipId?:string|null; readonly startFrame:number; readonly endFrame:number; readonly blocking:boolean; }
export type TimelineMultiTrackConflictCode = "missing-session-id" | "missing-selection" | "missing-anchor-clip" | "unknown-selected-clip" | "unknown-anchor-clip" | "duplicate-track-id" | "duplicate-clip-id" | "unknown-track" | "locked-track" | "locked-clip" | "invalid-track-order" | "invalid-timeline-range" | "invalid-source-range" | "invalid-operation" | "invalid-delta" | "invalid-pivot" | "pivot-intersects-clip" | "timeline-underflow" | "timeline-overflow" | "minimum-duration-violation" | "collision-detected" | "sync-offset-violation" | "link-group-violation" | "empty-affected-set";
export interface TimelineMultiTrackConflict { readonly code:TimelineMultiTrackConflictCode; readonly message:string; readonly clipId?:string|null; readonly trackId?:string|null; readonly linkGroupId?:string|null; readonly blocking:boolean; }
export interface TimelineMultiTrackPreview { readonly operation:MultiTrackEditOperation; readonly requestedDeltaFrames:number; readonly resolvedDeltaFrames:number; readonly pivotFrame:number; readonly previewPivotFrame:number; readonly affectedClipIds:readonly string[]; readonly affectedTrackIds:readonly string[]; readonly changes:readonly MultiTrackClipChange[]; readonly collisions:readonly MultiTrackCollision[]; readonly conflicts:readonly TimelineMultiTrackConflict[]; readonly snapped:boolean; readonly snapTargetId:string|null; readonly snapTargetFrame:number|null; readonly clamped:boolean; readonly blocked:boolean; }
export interface TimelineMultiTrackSnapResolver { resolveMultiTrackDelta(request:{ readonly operation:MultiTrackEditOperation; readonly anchorClip:MultiTrackTimelineClip; readonly pivotFrame:number; readonly requestedDeltaFrames:number; readonly affectedClipIds:readonly string[]; readonly excludedOwnerIds:readonly string[]; }):{ readonly resolvedDeltaFrames:number; readonly snapped:boolean; readonly targetId:string|null; readonly targetFrame:number|null; }; }
export interface TimelineMultiTrackCommitResult { readonly sessionId:string; readonly operation:MultiTrackEditOperation; readonly committed:boolean; readonly requestedDeltaFrames:number; readonly resolvedDeltaFrames:number; readonly affectedClipIds:readonly string[]; readonly affectedTrackIds:readonly string[]; readonly changes:readonly MultiTrackClipChange[]; readonly conflicts:readonly TimelineMultiTrackConflict[]; }
export interface TimelineMultiTrackEditSnapshot { readonly contractVersion:typeof TIMELINE_MULTI_TRACK_EDIT_CONTRACT_VERSION; readonly version:number; readonly status:TimelineMultiTrackEditStatus; readonly configured:boolean; readonly session:TimelineMultiTrackEditSession|null; readonly preview:TimelineMultiTrackPreview|null; readonly lastCommit:TimelineMultiTrackCommitResult|null; readonly linkGroups:readonly MultiTrackLinkGroup[]; readonly syncRelations:readonly MultiTrackSyncRelation[]; readonly conflicts:readonly TimelineMultiTrackConflict[]; }
export interface TimelineMultiTrackEditEvent { readonly type:TimelineMultiTrackEditEventType; readonly snapshot:TimelineMultiTrackEditSnapshot; }
export type TimelineMultiTrackEditListener=(event:TimelineMultiTrackEditEvent)=>void;
